version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 958526037165.dkr.ecr.us-west-1.amazonaws.com
    
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t webservicecourseworkreponew .
      - echo Tagging the current green image as blue if it exists...
      - docker pull 958526037165.dkr.ecr.ap-south-1.amazonaws.com/webservicecourseworkrepo:green || true
      - docker tag webservicecourseworkreponew:latest 958526037165.dkr.ecr.us-west-1.amazonaws.com/webservicecourseworkreponew:latest
      - echo Tagging the Docker image as green...
      - docker push 958526037165.dkr.ecr.us-west-1.amazonaws.com/webservicecourseworkreponew:latest

  post_build:
    commands:
      - echo Pushing the Docker image with blue tag to ECR if it exists...
      - docker push 958526037165.dkr.ecr.ap-south-1.amazonaws.com/webservicecourseworkrepo:latest
      - docker push 958526037165.dkr.ecr.ap-south-1.amazonaws.com/webservicecourseworkrepo:blue || true
      - docker push 958526037165.dkr.ecr.ap-south-1.amazonaws.com/webservicecourseworkrepo:green
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"958526037165.dkr.ecr.ap-south-1.amazonaws.com/webservicecourseworkrepo:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json



