version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 958526037165.dkr.ecr.ap-south-1.amazonaws.com
    
  build:
    commands:
      - docker build -t webservicecourseworkrepo .
      - docker tag webservicecourseworkrepo:latest 958526037165.dkr.ecr.ap-south-1.amazonaws.com/webservicecourseworkrepo:latest
  post_build:
    commands:
      - docker push 958526037165.dkr.ecr.ap-south-1.amazonaws.com/webservicecourseworkrepo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
